apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 25 min past the hour, 08:00-19:00, Mon-Fri
  schedule: '25 0,2,4,6,8,10 * * 1-5'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'department_users_sync_ad_data']
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: DATABASE_URL
                - name: ASCENDER_DEACTIVATE_EXPIRED
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: ASCENDER_DEACTIVATE_EXPIRED
                - name: DORMANT_ACCOUNT_DAYS
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: DORMANT_ACCOUNT_DAYS
                - name: DORMANT_ACCOUNT_DEACTIVATE
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: DORMANT_ACCOUNT_DEACTIVATE
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: AZURE_TENANT_ID
                - name: MS_GRAPH_API_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: MS_GRAPH_API_CLIENT_ID
                - name: MS_GRAPH_API_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: MS_GRAPH_API_CLIENT_SECRET
                - name: AZURE_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: AZURE_CONNECTION_STRING
