language: python
os: linux
dist: bionic
cache: pip
python:
  - "3.7"
services:
    - postgresql
    - docker
addons:
    postgresql: "11"
    apt:
        packages:
            - gdal-bin
            - postgresql-11-postgis-2.5
branches:
    only:
        - master
env:
    global:
        - SECRET_KEY="SecretKeyForTravisCI"
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
before_install:
    - docker build -t dbcawa/it-assets .
    - pip install --upgrade pip
    - pip install poetry
install:
    - poetry config virtualenvs.create false
    - poetry install --no-interaction --no-ansi
before_script:
    - psql -U postgres -c "create extension postgis"
    - psql -U postgres -c "create database travis_ci_test"
    - psql -U postgres -c "create database test_travis_ci_test"
    - psql -U postgres -d test_travis_ci_test -c "create extension citext"
script:
    - python manage.py test --keepdb
