sudo: required
language: python
cache: pip
dist: trusty
python:
    - 3.6
    - 3.7
services:
    - postgresql
    - docker
addons:
    postgresql: 9.5
    apt:
        packages:
            - postgresql-9.5-postgis-2.3
branches:
    only:
        - master
env:
    global:
        - SECRET_KEY="SecretKeyForTravisCI"
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install six
    - pip install -r requirements.txt
before_script:
    - psql -c 'create extension postgis' -U postgres
    - psql -c 'create database travis_ci_test;' -U postgres
    - python manage.py migrate --noinput
script:
    - python manage.py test
deploy:
    provider: script
    script: bash .travis_build.sh
    on:
        branch: master
        condition: $TRAVIS_PULL_REQUEST = false
