# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      PYTHON_VERSION: '3.7'
  maxParallel: 3

variables:
  secret_key: SecretKeyForAzurePipeline
  database_url: postgis://postgres@localhost:5433/ci_test

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

- task: PythonScript@0
  displayName: 'Export project path'
  inputs:
    scriptSource: 'inline'
    script: |
      """Search all subdirectories for `manage.py`."""
      from glob import iglob
      from os import path
      # Python >= 3.5
      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
      if not manage_py:
          raise SystemExit('Could not find a Django project')
      project_location = path.dirname(path.abspath(manage_py))
      print('Found Django project in', project_location)
      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))

- script: |
    sudo apt update
    sudo apt install --no-install-recommends -y postgis postgresql-12-postgis-3
  displayName: 'Install PostreSQL 12 and PostGIS 3'

- script: |
    sudo pg_ctlcluster 12 main start
    pg_lsclusters
    sudo psql -h localhost -p 5433 -U postgres -d template1 -c "create extension postgis"
    sudo psql -h localhost -p 5433 -U postgres -d template1 -c "create extension citext"
    sudo psql -h localhost -p 5433 -U postgres -c "create database ci_test"
    sudo psql -h localhost -p 5433 -U postgres -c "create database test_ci_test"
  displayName: 'Create test database'

- script: |
    pip install --upgrade pip
    pip install poetry
    poetry config virtualenvs.create false
    poetry install --no-interaction --no-ansi
  displayName: 'Install prerequisites'

- script: |
    pushd '$(projectRoot)'
    python manage.py test --no-input
  displayName: 'Run tests'
