apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../template
nameSuffix: -deptusers-sync-freshservice
patches:
- target:
    group: batch
    version: v1
    kind: CronJob
    name: itassets-cronjob
  path: patch.yaml
