apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 19:05, Mon-Fri
  schedule: "5 11 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: itassets-cronjob
            args: ["manage.py", "department_users_sync_freshservice"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: DATABASE_URL
            - name: FRESHSERVICE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: FRESHSERVICE_ENDPOINT
            - name: FRESHSERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: FRESHSERVICE_API_KEY
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: AZURE_TENANT_ID
            - name: MS_GRAPH_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: MS_GRAPH_API_CLIENT_ID
            - name: MS_GRAPH_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: MS_GRAPH_API_CLIENT_SECRET
