apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 18:33, Mon-Fri
  schedule: "33 10 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ["manage.py", "department_users_audit_employee_ids"]
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: DATABASE_URL
                - name: FOREIGN_DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_DB_HOST
                - name: FOREIGN_DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_DB_PORT
                - name: FOREIGN_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_DB_NAME
                - name: FOREIGN_DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_DB_USERNAME
                - name: FOREIGN_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_DB_PASSWORD
                - name: FOREIGN_SCHEMA
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_SCHEMA
                - name: FOREIGN_SERVER
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_SERVER
                - name: FOREIGN_TABLE
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_TABLE
