apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  schedule: "20,50 8-18 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: itassets-cronjob
            args: ["manage.py", "check_onprem_accounts", "--container", "azuread", "--path", "adusers.json"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: DATABASE_URL
            - name: AZURE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: AZURE_CONNECTION_STRING
