apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 10/40 min past the hour, 07:00-19:00, Mon-Fri
  schedule: '10,40 0-10,23 * * 1-5'
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'check_ascender_accounts']
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: DATABASE_URL
                - name: EMAIL_HOST
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: EMAIL_HOST
                - name: EMAIL_PORT
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: EMAIL_PORT
                - name: ADMIN_EMAILS
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: ADMIN_EMAILS
                - name: ASCENDER_CREATE_AZURE_AD
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: ASCENDER_CREATE_AZURE_AD
                - name: ASCENDER_CREATE_AZURE_AD_LIMIT_DAYS
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: ASCENDER_CREATE_AZURE_AD_LIMIT_DAYS
                - name: FOREIGN_DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_DB_HOST
                - name: FOREIGN_DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_DB_PORT
                - name: FOREIGN_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_DB_NAME
                - name: FOREIGN_DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_DB_USERNAME
                - name: FOREIGN_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_DB_PASSWORD
                - name: FOREIGN_SCHEMA
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_SCHEMA
                - name: FOREIGN_SERVER
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_SERVER
                - name: FOREIGN_TABLE
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: FOREIGN_TABLE
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: AZURE_TENANT_ID
                - name: MS_GRAPH_API_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: MS_GRAPH_API_CLIENT_ID
                - name: MS_GRAPH_API_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: MS_GRAPH_API_CLIENT_SECRET
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: SENTRY_DSN
                - name: SENTRY_ENVIRONMENT
                  value: 'prod'
                - name: SENTRY_CRON_CHECK_ASCENDER
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: SENTRY_CRON_CHECK_ASCENDER
