# Generated by Django 5.2.12 on 2026-04-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0008_alter_departmentuser_azure_ad_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITSystemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id_name', models.CharField(max_length=255, unique=True, verbose_name='System ID - Name')),
                ('division', models.PositiveSmallIntegerField(choices=[(1, 'Botanic Gardens and Parks Authority'), (2, 'Conservation and Parks Commission'), (3, 'DBCA Biodiversity and Conservation Science'), (4, 'DBCA Strategy and Governance'), (5, 'Parks and Wildlife Service'), (6, 'Rottnest Island Authority'), (7, 'Zoological Parks Authority'), (8, 'Nature-based Tourism Branch')], verbose_name='Division')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Production'), (2, 'Production (Legacy)'), (3, 'Decommissioned'), (4, 'Draft'), (5, 'Unknown')], default=1, verbose_name='Status')),
                ('seasonality', models.PositiveSmallIntegerField(choices=[(1, 'Bushfire season'), (2, 'End of financial year'), (3, 'Annual reporting'), (4, 'School holidays'), (5, 'Default')], default=5, verbose_name='Seasonality')),
                ('availability', models.PositiveSmallIntegerField(choices=[(1, '24/7/365'), (2, 'Business hours')], default=2, verbose_name='Availability')),
                ('description', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='URL to web application', max_length=2048, null=True)),
                ('file_store_link', models.CharField(blank=True, help_text='URL to file store', max_length=2048, null=True, verbose_name='File Store Link')),
                ('vital_records', models.BooleanField(default=False)),
                ('disposal_authority', models.CharField(blank=True, max_length=255, null=True, verbose_name='Disposal Authority')),
                ('retention_and_disposal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Retention and Disposal')),
                ('sensitivity', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Official'), (2, 'Official Sensitive')], default=1, null=True, verbose_name='Sensitivity')),
                ('system_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Application'), (2, 'Infrastructure'), (3, 'Platform')], default=1, null=True, verbose_name='System Type')),
                ('ubcs', models.CharField(blank=True, max_length=255, null=True, verbose_name='UBCS')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('business_service_owner', models.ForeignKey(blank=True, help_text='IT system business service owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems_business_service_owner_of', to='organisation.departmentuser', verbose_name='Business Service Owner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_created_by', to='organisation.departmentuser', verbose_name='Created by')),
                ('information_custodian', models.ForeignKey(blank=True, help_text='IT system information custodian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems_information_custodian_of', to='organisation.departmentuser', verbose_name='Information Custodian')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_modified_by', to='organisation.departmentuser', verbose_name='Modified by')),
                ('system_owner', models.ForeignKey(blank=True, help_text='IT system owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems_owner_of', to='organisation.departmentuser', verbose_name='System Owner')),
                ('technology_custodian', models.ForeignKey(blank=True, help_text='IT system technology custodian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems_technology_custodian_of', to='organisation.departmentuser', verbose_name='Technology Custodian')),
            ],
        ),
    ]
