# Generated by Django 5.2.12 on 2026-04-14 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0001_initial'),
        ('organisation', '0008_alter_departmentuser_azure_ad_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itsystemrecord',
            options={'verbose_name': 'IT System', 'verbose_name_plural': 'IT Systems Register'},
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_created_by', to='organisation.departmentuser', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_modified_by', to='organisation.departmentuser', verbose_name='Modified by'),
        ),
    ]
