# Generated by Django 5.2.12 on 2026-04-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0002_alter_itsystemrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itsystemrecord',
            options={'verbose_name': 'IT System', 'verbose_name_plural': 'IT Systems'},
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='created_by',
            field=models.EmailField(default='default@default.com', editable=False, max_length=254, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='modified_by',
            field=models.EmailField(editable=False, max_length=254, verbose_name='Modified By'),
        ),
    ]
