# Generated by Django 5.2.12 on 2026-04-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0003_alter_itsystemrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='file_store_link',
            field=models.URLField(blank=True, help_text='URL to file store', max_length=2048, null=True, verbose_name='File Store Link'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='link',
            field=models.URLField(blank=True, help_text='URL to web application', max_length=2048, null=True),
        ),
    ]
