# Generated by Django 5.2.12 on 2026-04-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0004_alter_itsystemrecord_file_store_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsystemrecord',
            name='system_id_name',
        ),
        migrations.AddField(
            model_name='itsystemrecord',
            name='name',
            field=models.CharField(default='defaultval', max_length=250, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itsystemrecord',
            name='system_id',
            field=models.CharField(default='T01', editable=False, max_length=5, unique=True, verbose_name='System ID'),
            preserve_default=False,
        ),
    ]
