# Generated by Django 5.2.12 on 2026-04-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0005_remove_itsystemrecord_system_id_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='system_id',
            field=models.CharField(max_length=5, unique=True, verbose_name='System ID'),
        ),
    ]
