# Generated by Django 5.2.12 on 2026-04-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0006_alter_itsystemrecord_system_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='system_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='System ID'),
        ),
    ]
