# Generated by Django 5.2.12 on 2026-04-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0007_alter_itsystemrecord_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Botanic Gardens and Parks Authority'), (2, 'Conservation and Parks Commission'), (3, 'DBCA Biodiversity and Conservation Science'), (4, 'DBCA Strategy and Governance'), (5, 'Parks and Wildlife Service'), (6, 'Rottnest Island Authority'), (7, 'Zoological Parks Authority'), (8, 'Nature-based Tourism Branch')], null=True, verbose_name='Division'),
        ),
    ]
