# Generated by Django 5.2.12 on 2026-04-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0008_alter_itsystemrecord_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
