# Generated by Django 5.2.12 on 2026-04-21 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0009_alter_itsystemrecord_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
            },
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_division', to='itsystems.division', verbose_name='Division'),
        ),
    ]
