# Generated by Django 5.2.12 on 2026-04-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0010_division_alter_itsystemrecord_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
