# Generated by Django 5.2.12 on 2026-04-28 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0012_availability_seasonality_sensitivity_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='availability',
            field=models.ForeignKey(blank=True, help_text='Availability', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_availability', to='itsystems.availability', verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Division', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_division', to='itsystems.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='seasonality',
            field=models.ForeignKey(blank=True, help_text='Seasonality', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_seasonality', to='itsystems.seasonality', verbose_name='Seasonality'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='sensitivity',
            field=models.ForeignKey(blank=True, help_text='Sensitivity', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_sensitivity', to='itsystems.sensitivity', verbose_name='Sensitivity'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Status', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_status', to='itsystems.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='system_type',
            field=models.ForeignKey(blank=True, help_text='System Type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_system_type', to='itsystems.systemtype', verbose_name='System Type'),
        ),
    ]
