# Generated by Django 5.2.12 on 2026-04-28 08:12

import django.db.models.deletion
import itsystems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0013_alter_itsystemrecord_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='availability',
            field=models.ForeignKey(default=itsystems.models.Availability.get_default_pk, help_text='Availability', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_availability', to='itsystems.availability', verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='seasonality',
            field=models.ForeignKey(default=itsystems.models.Seasonality.get_default_pk, help_text='Seasonality', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_seasonality', to='itsystems.seasonality', verbose_name='Seasonality'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='sensitivity',
            field=models.ForeignKey(blank=True, default=itsystems.models.Sensitivity.get_default_pk, help_text='Sensitivity', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_sensitivity', to='itsystems.sensitivity', verbose_name='Sensitivity'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='status',
            field=models.ForeignKey(default=itsystems.models.Status.get_default_pk, help_text='Status', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_status', to='itsystems.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='system_type',
            field=models.ForeignKey(blank=True, default=itsystems.models.SystemType.get_default_pk, help_text='System Type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_system_type', to='itsystems.systemtype', verbose_name='System Type'),
        ),
    ]
