# Generated by Django 5.2.12 on 2026-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0014_alter_itsystemrecord_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='vital_records',
            field=models.BooleanField(default=False, verbose_name='Vital Records'),
        ),
    ]
