apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -uat
resources:
- ../../base
- ingress.yaml
secretGenerator:
- name: itassets-env
  type: Opaque
  envs:
    - .env
labels:
- includeSelectors: true
  pairs:
    app: itassets
    variant: uat
patches:
- path: clusterip_patch.yaml
- path: deployment_patch.yaml
- path: pdb_patch.yaml
