apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -uat
secretGenerator:
- name: itassets-env
  type: Opaque
  envs:
  - .env
resources:
- ../../base
- ingress.yaml
labels:
- includeSelectors: true
  pairs:
    variant: uat
patches:
- path: deployment_patch.yaml
- path: service_patch.yaml
- path: pdb_patch.yaml
