apiVersion: apps/v1
kind: Deployment
metadata:
  name: itassets-deployment
spec:
  template:
    spec:
      containers:
        - name: itassets
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: SECRET_KEY
            - name: ADMIN_EMAILS
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: ADMIN_EMAILS
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: EMAIL_HOST
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: EMAIL_PORT
            - name: AZURE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: AZURE_ACCOUNT_NAME
            - name: AZURE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: AZURE_ACCOUNT_KEY
            - name: AZURE_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: AZURE_CONTAINER
            - name: AZURE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: AZURE_CONNECTION_STRING
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: AZURE_TENANT_ID
            - name: MS_GRAPH_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: MS_GRAPH_API_CLIENT_ID
            - name: MS_GRAPH_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: MS_GRAPH_API_CLIENT_SECRET
            - name: ASCENDER_DEACTIVATE_EXPIRED
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: ASCENDER_DEACTIVATE_EXPIRED
            - name: ASCENDER_CREATE_AZURE_AD
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: ASCENDER_CREATE_AZURE_AD
            - name: ASCENDER_CREATE_AZURE_AD_LIMIT_DAYS
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: ASCENDER_CREATE_AZURE_AD_LIMIT_DAYS
            - name: DORMANT_ACCOUNT_DAYS
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: DORMANT_ACCOUNT_DAYS
            - name: DORMANT_ACCOUNT_DEACTIVATE
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: DORMANT_ACCOUNT_DEACTIVATE
            - name: FOREIGN_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: FOREIGN_DB_HOST
            - name: FOREIGN_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: FOREIGN_DB_PORT
            - name: FOREIGN_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: FOREIGN_DB_NAME
            - name: FOREIGN_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: FOREIGN_DB_USERNAME
            - name: FOREIGN_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: FOREIGN_DB_PASSWORD
            - name: FOREIGN_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: FOREIGN_SCHEMA
            - name: FOREIGN_SERVER
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: FOREIGN_SERVER
            - name: FOREIGN_TABLE
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: FOREIGN_TABLE
            - name: FOREIGN_TABLE_CC_MANAGER
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: FOREIGN_TABLE_CC_MANAGER
            - name: ASCENDER_SFTP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: ASCENDER_SFTP_HOSTNAME
            - name: ASCENDER_SFTP_PORT
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: ASCENDER_SFTP_PORT
            - name: ASCENDER_SFTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: ASCENDER_SFTP_USERNAME
            - name: ASCENDER_SFTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: ASCENDER_SFTP_PASSWORD
            - name: ASCENDER_SFTP_DIRECTORY
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: ASCENDER_SFTP_DIRECTORY
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: SENTRY_DSN
            - name: SENTRY_SAMPLE_RATE
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: SENTRY_SAMPLE_RATE
            - name: SENTRY_TRANSACTION_SAMPLE_RATE
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: SENTRY_TRANSACTION_SAMPLE_RATE
            - name: SENTRY_PROFILES_SAMPLE_RATE
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: SENTRY_PROFILES_SAMPLE_RATE
            - name: SENTRY_ENVIRONMENT
              value: 'prod'
            - name: GEOSERVER_URL
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: GEOSERVER_URL
            - name: REDIS_CACHE_HOST
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: REDIS_CACHE_HOST
            - name: API_RESPONSE_CACHE_SECONDS
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: API_RESPONSE_CACHE_SECONDS
