apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
secretGenerator:
- name: itassets-env
  type: Opaque
  envs:
  - .env
resources:
  - ../../base
  - ingress.yaml
  - cronjobs/ascender-csv-upload
  - cronjobs/deptusers-audit-email
labels:
- includeSelectors: true
  pairs:
    app: itassets
    variant: prod
images:
- name: ghcr.io/dbca-wa/it-assets
  newTag: 2.4.4
patches:
- path: clusterip_patch.yaml
- path: deployment_patch.yaml
- path: pdb_patch.yaml
