apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
  - ../../base
  - ingress.yaml
  - cronjobs/ascender-csv-upload
  - cronjobs/deptusers-audit-email
  - cronjobs/deptusers-audit-employeeid
  - cronjobs/deptusers-changes-report
  - cronjobs/deptusers-check-ascender
  - cronjobs/deptusers-check-azure
  - cronjobs/deptusers-check-onprem
  - cronjobs/deptusers-sync-ad
  - cronjobs/deptusers-sync-freshservice
  - cronjobs/m365-licence-check
  - cronjobs/storage-usage
  - cronjobs/update-ccm
  - postgres_fdw_pvc.yaml
secretGenerator:
  - name: itassets-env
    type: Opaque
    envs:
      - .env
labels:
  - includeSelectors: true
    pairs:
      variant: prod
patches:
  - path: clusterip_patch.yaml
  - path: deployment_patch.yaml
  - path: deployment_hpa_patch.yaml
  - path: pdb_patch.yaml
  - path: postgres_fdw_patch.yaml
  - path: postgres_fdw_service_patch.yaml
images:
  - name: ghcr.io/dbca-wa/it-assets
    newTag: 2.4.28
