apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itassets-postgres-fdw-data
spec:
  storageClassName: managed-csi-retain-zrs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
