apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # Every minute
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'department_users_signins', '--logging']
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: DATABASE_URL
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: AZURE_TENANT_ID
                - name: MS_GRAPH_API_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: MS_GRAPH_API_CLIENT_ID
                - name: MS_GRAPH_API_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: itassets-env-prod
                      key: MS_GRAPH_API_CLIENT_SECRET
