apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  schedule: "1 2 * * 3,6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: itassets-cronjob
            args: ["manage.py", "site_storage_upload"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: DATABASE_URL
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: AZURE_TENANT_ID
            - name: MS_GRAPH_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: MS_GRAPH_API_CLIENT_ID
            - name: MS_GRAPH_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: MS_GRAPH_API_CLIENT_SECRET
            - name: AZURE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: itassets-env-prod
                  key: AZURE_CONNECTION_STRING
