apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
  labels:
    app: itassets-cronjob
spec:
  schedule: ""
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      activeDeadlineSeconds: 300
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: itassets-cronjob
            image: ghcr.io/dbca-wa/it-assets
            command: ["python"]
            args: ["--version"]
            env:
            - name: TZ
              value: "Australia/Perth"
            securityContext:
              runAsNonRoot: true
              privileged: false
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
            volumeMounts:
              - mountPath: /tmp
                name: tmpfs-ram
          volumes:
            - name: tmpfs-ram
              emptyDir:
                medium: "Memory"
